### ISSUE TITLE
Impossible to use this Chrome Extension with an Antivirus 

### ISSUE THREAD

**Issue by Almaric78** [7killer/ITYC-Dashboard#17]
Hello, it is not possible to use the application with an Antivirus like Kapersky, the plugin does not find the name of the boat which remains marked only 'unknown'

Thanks for the app.

**Comment by 7killer** [comment]
Hello,
As explain multiples times,
The ityc dashboard uses  technology which can be consider as a troyan for some antivirus.
I invite you to consult the help of your antivirus tools to add an exception.

For Kapersky, an exception can be added as describes in this link :
https://www.youtube.com/watch?v=lLSYrA1l_WM
https://support.kaspersky.com/help/Kaspersky/Win21.5/en-US/227390.htm

If you the kapersky chrome extension , you have to add an exception too.
